server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/autostok
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

flyway:
  url: jdbc:postgresql://localhost:5432/autostok
  user: postgres
  password: postgres
  locations: classpath:db/migration